### ISSUE TITLE
Package naming

### ISSUE THREAD

**Issue by lorenzwalthert** [mlverse/cuml4r#75]
Hi @yitao-li, cool work 🥳 .I know you already published on CRAN but I was just wondering if the package should be renamed {cuml} to make it consistent with existing R ML packages from the tidy/mlverse:

* keras (and not kerasR, which is another R interface)
* tensorflow
* torch (and not rTorch, which is another R interface)
* tabnet
* ...

Given that this package is not yet widely used or advertised, I name change would be relatively 'cheap'. I know I have no stake in this what so ever, just thinking out loud. Feel free to close with no comment :-)

**Comment by yitao-li** [comment]
I see. That's a great suggestion! Thanks. I didn't even realize there was this naming convention : )

**Comment by yitao-li** [comment]
I'm inclined to rename `cuml4r` to `cuml`, but then realized there are some places where `cuml` the C++ library and the `cuml4r` the R package are mentioned in the same sentence or in the same paragraph within the roxygen docs. This makes the `cuml4r` to `cuml` renaming a bit challenging.

**Comment by lorenzwalthert** [comment]
I see. I think alternatively, you could write „the R package“ and „the C++ package“ to distinguish. And/or use {cuml} to refer to the R package (another new convention not backed by the tidyverse style). I think the benefits of the convention may outweigh the drawbacks in these situations.
