### ISSUE TITLE
reduce api elements that can result in user error. 

### ISSUE THREAD

**Issue by topepo** [mlverse/cuml4r#79]
We'd like users to have fewer places to accidentally do the wrong thing. For example, in the random forest implementation:

* The user should not have to set the mode (which defaults to classification). Since the data can be either numeric or factor, their data can be used to internally set the mode. 
* Similarly, the splitting criterion is a 1:1 relationship with mode. The function can set this internally. 

I would remove these two arguments and find other potential pain points that users might experience. 

Other suggestions in the same spirit:

* Don't default to 8 streams. Users should opt-in to parallel processing. This is especially true for models that might be resampled; users make unwittingly specify 8^2 parallel works without realizing it. 
* Make the default for `max_leaves` to be `Inf` instead of a nonsensical value of -1. Even if the underlying code wants -1, don't ask users to remember special magic numbers for arguments.

**Comment by yitao-li** [comment]
Re: split criterion -- only the default value has a 1:1 relation with mode.
